### ISSUE TITLE
PROGMEM access

### ISSUE THREAD

**Issue by pedroke** [SmarterDM/micro-aes#5]
Please correct me if I'm wrong, but doesn't the usage of PROGMEM expect e.g. pgm_read_byte to retrieve the data from program memory? Would it work the way it is currently implemented? I think with the PROGMEM directive, the references to arrays will only result in useless garbage, or not?

**Comment by AndrewCarterUK** [comment]
Yes it does, apologies.

We have tested this on AVR hardware, but it seems the `ifdef` wasn't triggering so we were saved.

Thanks very much - should be fixed by #6
